apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: polkadot-metrics
  template:
    metadata:
      labels:
        app: polkadot-metrics
    spec:
      containers:
        - name: polkadot-metrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
