{
 "title": "Polkadot Metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Era",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polkadot_current_era{chain=\"polkadot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Session Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polkadot_session_current_index{chain=\"polkadot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polkadot_system_block_number{chain=\"polkadot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Rewards",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "polkadot_validator_reward_points{chain=\"polkadot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}