apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: "Prometheus"
        type: "prometheus"
        url: "http://polkadot-metrics.default.svc.cluster.local:9090"
        access: "proxy"
        isDefault: true
        editable: true
