apiVersion: apps/v1
kind: Deployment
metadata:
  name: polkadot-metrics
spec:
  replicas: 1  # Start with 3 replicas; you can scale further as needed.
  selector:
    matchLabels:
      app: polkadot-metrics
  template:
    metadata:
      labels:
        app: polkadot-metrics
    spec:
      containers:
        - name: polkadot-metrics
          image: ashhar001/polkadot-metrics:v5
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 20
