apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: polkadot-metrics-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: polkadot-metrics
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
